In [ ]:
import tensorflow as tf
import pandas as pd
import numpy as np
import shutil
import math
import multiprocessing
from datetime import datetime
from tensorflow.python.feature_column import feature_column
#tf.enable_eager_execution()
print(tf.__version__)
sess = tf.Session()
logdir = r'E:\my_proj\fog_recognition\recognition_pre_fog_tf\notebook\log'

In [78]:
writer = tf.summary.FileWriter(logdir, tf.get_default_graph())

In [73]:
with tf.name_scope('hidden') as scope:
    a = tf.constant(5, name='alpha')
    W = tf.Variable(tf.random_uniform([1, 2], -1.0, 1.0), name='weights')
    b = tf.Variable(tf.zeros([1]), name='biases')

with tf.variable_scope('hidden222') as scope:
    a = tf.constant(5, name='alpha')
    W = tf.Variable(tf.random_uniform([1, 2], -1.0, 1.0), name='weights')
    b = tf.Variable(tf.zeros([1]), name='biases')

In [82]:
with tf.variable_scope("my_scope",reuse=tf.AUTO_REUSE):
    v1 = tf.get_variable("var1", [1], dtype=tf.float32)
    v2 = tf.Variable(1, name="var2", dtype=tf.float32)
    a = tf.add(3.0, 5)
    b =tf.get_variable("add", [1], dtype=tf.float32)

print(v1.name)  # my_scope/var1:0
print(v2.name)  # my_scope/var2:0
print(a.name)   # my_scope/Add:0
print(b.name)

my_scope/var1:0
my_scope_34/var2:0
my_scope_34/Add:0
my_scope/add_1:0


In [143]:
li = list(zip(list('abcde'),list("12345")))
li =[{i:j} for i,j in li]
li = [{i:i} for i in list("abcdefgh")]

In [172]:
import pandas

In [173]:
df = pandas.DataFrame()
df['A']=list("abcdefg")
df['B']=list("1234567")
data={"df":[df,df]}

In [178]:
#ds=tf.data.Dataset.from_tensors(dict(li))
ds=tf.data.Dataset.from_tensor_slices((list('abcde'),list("12345")))
ds=tf.data.Dataset.from_tensor_slices({"df":[1,2]})

In [170]:
#ds = tf.data.Dataset.from_tensor_slices((dict(features), labels))
#ds = tf.data.Dataset.from_tensor_slices((list('abcde'),list("12345")))
ds

<TensorSliceDataset shapes: ((), ()), types: (tf.string, tf.string)>

In [179]:

it = ds.make_one_shot_iterator()
ne = it.get_next()
for i in range(4):
    print(sess.run(ne))

{'df': 1}
{'df': 2}


OutOfRangeError: End of sequence
	 [[node IteratorGetNext_14 (defined at <ipython-input-179-c4e08b28297a>:3)  = IteratorGetNext[output_shapes=[[]], output_types=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_12)]]

Caused by op 'IteratorGetNext_14', defined at:
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\kernelapp.py", line 478, in start
    self.io_loop.start()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\IPython\core\interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\IPython\core\interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-179-c4e08b28297a>", line 3, in <module>
    ne = it.get_next()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2107, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[node IteratorGetNext_14 (defined at <ipython-input-179-c4e08b28297a>:3)  = IteratorGetNext[output_shapes=[[]], output_types=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_12)]]


In [342]:
def my_func(x):
    df = pandas.read_csv(x.decode())
    # x will be a numpy array with the contents of the placeholder below
    print(df.head())
    print(x.__class__)
    print(x,x.decode())
    return df.iloc[:,2].values,np.float32(df.iloc[:,3].values)
inputs = tf.placeholder(tf.string)
y = tf.py_func(my_func, [inputs], [tf.string,tf.float32])

In [ ]:
from pyspark.sql import SparkSession
from pyspark.sql.functions import col
 
# 初始化
spark = SparkSession.builder.master("local[*]").appName("FiratApp").getOrCreate()
 
# 下面两句都可以获取0到9的数据
# data = spark.createDataFrame(map(lambda x: (x,), range(10)), ["id"])
data = spark.range(0, 10).select(col("id").cast("double"))
 
# 求和
data.agg({'id': 'sum'}).show()
 

In [ ]:
df=spark.read.csv('E:\\my_proj\\fog_recognition\\ExtendFoGData\\fixed_data\\VideoMark\\20161223_1_1_result_1.csv',header=True)

In [ ]:
df.show()

In [365]:
df.schema

StructType(List(StructField(label_start_time,StringType,true),StructField(label_end_time,StringType,true),StructField(gait_type,StringType,true),StructField(label_confidence,StringType,true),StructField(stimulate_type,StringType,true),StructField(start_time,StringType,true),StructField(end_time,StringType,true),StructField(unit_confidence,StringType,true)))

In [364]:
df.foreach(lambda it:len(it))

Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 12.0 failed 1 times, most recent failure: Lost task 0.0 in stage 12.0 (TID 19, localhost, executor driver): org.apache.spark.SparkException: Python worker failed to connect back.
	at org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:170)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:97)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:117)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:108)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:65)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.SocketTimeoutException: Accept timed out
	at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)
	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:135)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:164)
	... 14 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1887)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1875)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1874)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1874)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:926)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:926)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:2108)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2057)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:2046)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:49)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:737)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2061)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2082)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2101)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:2126)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:945)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:363)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:944)
	at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:166)
	at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
	at py4j.Gateway.invoke(Gateway.java:282)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:238)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.spark.SparkException: Python worker failed to connect back.
	at org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:170)
	at org.apache.spark.api.python.PythonWorkerFactory.create(PythonWorkerFactory.scala:97)
	at org.apache.spark.SparkEnv.createPythonWorker(SparkEnv.scala:117)
	at org.apache.spark.api.python.BasePythonRunner.compute(PythonRunner.scala:108)
	at org.apache.spark.api.python.PythonRDD.compute(PythonRDD.scala:65)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:324)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:288)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
	at org.apache.spark.scheduler.Task.run(Task.scala:121)
	at org.apache.spark.executor.Executor$TaskRunner$$anonfun$10.apply(Executor.scala:402)
	at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1360)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:408)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.net.SocketTimeoutException: Accept timed out
	at java.net.DualStackPlainSocketImpl.waitForNewConnection(Native Method)
	at java.net.DualStackPlainSocketImpl.socketAccept(DualStackPlainSocketImpl.java:135)
	at java.net.AbstractPlainSocketImpl.accept(AbstractPlainSocketImpl.java:409)
	at java.net.PlainSocketImpl.accept(PlainSocketImpl.java:199)
	at java.net.ServerSocket.implAccept(ServerSocket.java:545)
	at java.net.ServerSocket.accept(ServerSocket.java:513)
	at org.apache.spark.api.python.PythonWorkerFactory.createSimpleWorker(PythonWorkerFactory.scala:164)
	... 14 more


In [343]:
df = pandas.read_csv('E:\\my_proj\\fog_recognition\\ExtendFoGData\\fixed_data\\VideoMark\\20161223_1_1_result_1.csv')

In [345]:
sess.run(y,feed_dict={inputs:'E:\\my_proj\\fog_recognition\\ExtendFoGData\\fixed_data\\VideoMark\\20161223_1_1_result_1.csv'})

   label_start_time  label_end_time gait_type  label_confidence  \
0                 0               8         I               1.0   
1                12              13         D               0.2   
2                17              18         D               0.4   
3                19              25         D               0.6   
4                26              26         D               0.4   

   stimulate_type  start_time  end_time  unit_confidence  
0             NaN     3251751   3252650              0.4  
1             NaN     3252951   3253150              0.4  
2             NaN     3253451   3253650              0.4  
3             NaN     3253651   3254350              0.4  
4             NaN     3254351   3254450              0.4  
<class 'bytes'>
b'E:\\my_proj\\fog_recognition\\ExtendFoGData\\fixed_data\\VideoMark\\20161223_1_1_result_1.csv' E:\my_proj\fog_recognition\ExtendFoGData\fixed_data\VideoMark\20161223_1_1_result_1.csv


[array([b'I', b'D', b'D', b'D', b'D', b'J', b'H', b'H', b'D', b'C', b'H',
        b'A', b'J', b'H', b'H', b'D', b'H', b'H', b'D', b'H', b'G'],
       dtype=object),
 array([1. , 0.2, 0.4, 0.6, 0.4, 0.6, 1. , 0.8, 0.5, 0.3, 0.9, 0.6, 0.6,
        0.6, 0.9, 0.4, 0.6, 0.9, 0.4, 0.9, 1. ], dtype=float32)]

In [278]:
data_path =path.Path(r'E:\my_proj\fog_recognition\ExtendFoGData\fixed_data\VideoMark')
filenames = [str(i) for i in data_path.files()]
np.float32(9)

9.0

In [266]:
sess.run(tf.fft([12,34,13,56,78,99,23,67,85]))

array([466.99982 -1.4305115e-04j, -88.77441 +6.4565353e+01j,
        53.578655+8.3774681e+01j, -96.99994 +1.5588486e+01j,
       -47.304268-6.6527115e+01j, -47.304058+6.6527267e+01j,
       -96.99988 -1.5588434e+01j,  53.578537-8.3774551e+01j,
       -88.774414-6.4565300e+01j], dtype=complex64)

In [152]:
sys.path.append(r'E:\my_proj\GOOD_PROJECTS\tf_official_models\samples\core\get_started')
import iris_data

# Fetch the data
train, test = iris_data.load_data()
features, labels = train

In [138]:
tf.constant(5)
ds

<TensorSliceDataset shapes: ((), ()), types: (tf.string, tf.string)>

In [3]:
MODEL_NAME = 'reg-model-02'

TRAIN_DATA_FILES_PATTERN = 'data/train-*.csv'
VALID_DATA_FILES_PATTERN = 'data/valid-*.csv'
TEST_DATA_FILES_PATTERN = 'data/test-*.csv'

RESUME_TRAINING = False
PROCESS_FEATURES = True
MULTI_THREADING = True

HEADER = ['key','x','y','alpha','beta','target']
HEADER_DEFAULTS = [[0], [0.0], [0.0], ['NA'], ['NA'], [0.0]]

NUMERIC_FEATURE_NAMES = ['x', 'y']  

CATEGORICAL_FEATURE_NAMES_WITH_VOCABULARY = {'alpha':['ax01', 'ax02'], 'beta':['bx01', 'bx02']}
CATEGORICAL_FEATURE_NAMES = list(CATEGORICAL_FEATURE_NAMES_WITH_VOCABULARY.keys())

FEATURE_NAMES = NUMERIC_FEATURE_NAMES + CATEGORICAL_FEATURE_NAMES

TARGET_NAME = 'target'

UNUSED_FEATURE_NAMES = list(set(HEADER) - set(FEATURE_NAMES) - {TARGET_NAME})

In [3]:
import pandas
df_dataset = pandas.read_csv('data/train-data.csv',names=HEADER,skiprows=0)


In [23]:
tf.gfile.Glob(TRAIN_DATA_FILES_PATTERN),tf.gfile.Exists('data\\train-data.csv'),sess.run(tf.matching_files(TRAIN_DATA_FILES_PATTERN))

(['data\\train-data.csv'],
 True,
 array([b'data\\train-data.csv'], dtype=object))

In [25]:
data_dir = r'E:\my_proj\fog_recognition\ExtendFoGData\fixed_data\SignalETL4FoG'
filenames = tf.gfile.ListDirectory(data_dir)

In [26]:
#数据输入转换管道
X= tf.placeholder(tf.float32,shape=(None,2))
ds = tf.data.Dataset.from_tensor_slices(X)

# 迭代器部分
iterator = ds.make_initializable_iterator()
next_element = iterator.get_next()
init = iterator.make_initializer(ds)

sess.run(iterator.initializer,feed_dict={X:[[1.0,2],[4,6],[3,5],[7,8],[11,9]]})
for i in range(3):
    print(sess.run(next_element))
print("================================")   
sess.run(iterator.initializer,feed_dict={X:[[11.0,2],[41,6],[13,5],[27,48],[141,59]]})
for i in range(3):
    print(sess.run(next_element))
print("================================")
sess.run(init,feed_dict={X:[[81.0,2],[41,66],[13,75],[27,8],[41,5]]})
for i in range(3):
    print(sess.run(next_element))

[1. 2.]
[4. 6.]
[3. 5.]
[11.  2.]
[41.  6.]
[13.  5.]
[81.  2.]
[41. 66.]
[13. 75.]


In [27]:
# Define training and validation datasets with the same structure. 客户端的感觉
training_dataset = tf.data.Dataset.range(100).map(lambda x: x + tf.random_uniform([], -10, 10, tf.int64))
validation_dataset = tf.data.Dataset.range(50)

# A reinitializable iterator is defined by its structure. We could use the
# `output_types` and `output_shapes` properties of either `training_dataset`
# or `validation_dataset` here, because they are compatible.
iterator = tf.data.Iterator.from_structure(training_dataset.output_types,training_dataset.output_shapes)
next_element = iterator.get_next()
# 使用两个不同数据数据集来初始化迭代器
training_init_op = iterator.make_initializer(training_dataset)
validation_init_op = iterator.make_initializer(validation_dataset)

# Run 20 epochs in which the training dataset is traversed, followed by the validation dataset.
for _ in range(20):
  # Initialize an iterator over the training dataset.
    sess.run(training_init_op)
    for _ in range(100):
        print(sess.run(next_element))
  # Initialize an iterator over the validation dataset.
    sess.run(validation_init_op)
    for _ in range(50):
        print(sess.run(next_element))

-8
6
-2
-6
-3
-2
-1
15
13
11
1
15
3
5
22
19
14
7
26
10
14
25
30
13
23
31
28
33
22
23
38
33
39
27
33
25
37
36
45
32
32
31
37
38
51
52
43
37
43
47
51
48
42
47
58
52
50
53
57
60
51
64
52
71
61
68
68
62
76
78
60
69
80
71
68
66
71
77
78
87
82
82
86
76
76
93
85
91
83
88
89
93
99
85
90
99
87
100
99
107
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
6
-9
-8
-6
6
-3
4
4
-2
7
14
2
4
18
13
19
6
15
20
10
14
11
20
26
29
26
22
30
21
22
21
32
29
35
32
26
43
31
39
37
39
41
35
52
46
38
54
48
40
43
58
46
47
48
56
56
47
62
58
62
53
58
64
54
54
73
58
58
76
74
60
69
81
68
74
73
72
78
75
86
88
80
86
73
74
91
84
85
88
90
83
90
83
93
87
92
104
89
107
106
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
-8
-7
5
4
4
2
5
0
14
8
10
13
6
7
11
12
10
24
13
21
16
16
16
23
15
23
31
34
31
26
33
21
30
25
43
42
37
35
28
34
32
34
41
48
37
39

In [118]:
# Define training and validation datasets with the same structure.
training_dataset = tf.data.Dataset.range(100).map(lambda x: x + tf.random_uniform([], -10, 10, tf.int64)).repeat()
validation_dataset = tf.data.Dataset.range(50)

# A feedable iterator is defined by a handle placeholder and its structure. We
# could use the `output_types` and `output_shapes` properties of either
# `training_dataset` or `validation_dataset` here, because they have identical structure.
handle = tf.placeholder(tf.string, shape=[])
iterator = tf.data.Iterator.from_string_handle(handle, training_dataset.output_types, training_dataset.output_shapes)
next_element = iterator.get_next()

# You can use feedable iterators with a variety of different kinds of iterator (such as one-shot and initializable iterators).
training_iterator = training_dataset.make_one_shot_iterator()  # 直接从训练数据集上创建新的迭代器
validation_iterator = validation_dataset.make_initializable_iterator()

# The `Iterator.string_handle()` method returns a tensor that can be evaluated and used to feed the `handle` placeholder.
training_handle = sess.run(training_iterator.string_handle()) # 获得待输入迭代器的handle
validation_handle = sess.run(validation_iterator.string_handle())

# Loop forever, alternating between training and validation.
for _ in range(100):
  # Run 200 steps using the training dataset. Note that the training dataset is
  # infinite, and we resume from where we left off in the previous `while` loop iteration.
    for _ in range(200):
        sess.run(next_element, feed_dict={handle: training_handle}) # 用获得数据的handle喂作为handle的placeholder，进一步到next_element

  # Run one pass over the validation dataset.
    sess.run(validation_iterator.initializer)
    for _ in range(50):
        sess.run(next_element, feed_dict={handle: validation_handle})
        
# 总结一下就是并存三个迭代器对象，而不像之前只有一个，通过重新初始化便可多次复用；当前的情况就是，另外两个借助一个迭代器到达next_element;
# 像汇流一样。

In [6]:
import path
data_path =path.Path(r'E:\my_proj\fog_recognition\ExtendFoGData\fixed_data\VideoMark')
filenames = data_path.files()
def _parse_function(filename, label):
    image_string = tf.read_file(filename)
    #image_string=tf.data.TextLineDataset(filename).skip(1)
    #return image_string,label
    return filename.__class__.__name__+"st"

In [28]:
dataset = tf.data.Dataset.from_tensor_slices((filenames,list(range(len(filenames)))))
dataset = dataset.map(_parse_function)

iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

for _ in range(6):
    print(sess.run(next_element))

NameError: name '_parse_function' is not defined

In [ ]:
dataset = dataset.map( _parse_function)

In [ ]:
inc_dataset = tf.data.Dataset.range(100)
dec_dataset = tf.data.Dataset.range(0, -100, -1)
dataset = tf.data.Dataset.zip((inc_dataset, dec_dataset))
batched_dataset = dataset.batch(4)

iterator = batched_dataset.make_one_shot_iterator()
next_element = iterator.get_next()

print(sess.run(next_element))  # ==> ([0, 1, 2,   3],   [ 0, -1,  -2,  -3])
print(sess.run(next_element))  # ==> ([4, 5, 6,   7],   [-4, -5,  -6,  -7])
print(sess.run(next_element))  # ==> ([8, 9, 10, 11],   [-8, -9, -10, -11])

print("+============================================================+")
dataset = tf.data.Dataset.range(100)
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()
print(sess.run(next_element))
print(sess.run(next_element))
print(sess.run(next_element))
print(sess.run(next_element))

In [344]:
sess.run(tf.cast(random.choices([1,2,3,4,5,6,7,8],k=1)[0],tf.float32))

6.0

In [347]:
import random
random.randint(1,10)

li = [random.choices([1,2,3,4,5,6,7,8],k=random.randint(1,6)) for _ in range(10)]  # python 中的调用时急切执行的，这与tf中的节点不同

def f1(it):
    print('-->',it)
    return random.choices([1,2,3,4,5,6,7,8],k=1)[0] # 这个Python对象只在创建时被执行一次 random.randint(1,6)
    
# def _parse_function(filename):
#     #image_string = tf.read_file(filename)
#     #image_string=tf.data.TextLineDataset(filename).skip(1)
#     print(filename,random.randint(1,10))
#     #return image_string,label
#     return filename.__class__.__name__+"st"

ds = tf.data.Dataset.from_tensor_slices([random.choices([1,2,3,4,5,6,7,8],k=1) for _ in range(10)])

ds=ds.map(lambda it: tf.py_func(f1,[it],tf.int32))
print("=======================")
iterator = ds.make_one_shot_iterator()
next_element = iterator.get_next()
#print("=======================")
for _ in range(6):
    print(sess.run(next_element))

--> [3]
1
--> [2]
6
--> [1]
3
--> [4]
7
--> [3]
3
--> [6]
7


In [331]:
dataset = dataset.map(
    lambda filename, label: tuple(tf.py_func( _read_py_function, [filename, label], [tf.uint8, label.dtype])))
dataset = dataset.map(_resize_function)

TypeError: py_func() missing 2 required positional arguments: 'inp' and 'Tout'

In [240]:
dataset = tf.data.Dataset.range(100)
dataset = dataset.map(lambda x: tf.fill([tf.cast(x, tf.int32)], x))
#dataset = dataset.batch(1)
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

for _ in range(6):
    print(sess.run(next_element))
print("===========================")

dataset = tf.data.Dataset.range(100)
dataset = dataset.map(lambda x: tf.fill([tf.cast(x, tf.int32)], x))
dataset = dataset.padded_batch(4, padded_shapes=[None])
iterator = dataset.make_one_shot_iterator()

next_element = iterator.get_next()
for _ in range(3):
    print(sess.run(next_element))

[]
[1]
[2 2]
[3 3 3]
[4 4 4 4]
[5 5 5 5 5]
[[0 0 0]
 [1 0 0]
 [2 2 0]
 [3 3 3]]
[[4 4 4 4 0 0 0]
 [5 5 5 5 5 0 0]
 [6 6 6 6 6 6 0]
 [7 7 7 7 7 7 7]]
[[ 8  8  8  8  8  8  8  8  0  0  0]
 [ 9  9  9  9  9  9  9  9  9  0  0]
 [10 10 10 10 10 10 10 10 10 10  0]
 [11 11 11 11 11 11 11 11 11 11 11]]


In [348]:
norm = tf.random_normal([2, 3], mean=-1, stddev=4)

# Shuffle the first dimension of a tensor
c = tf.constant([[1, 2], [3, 4], [5, 6]])
shuff = tf.random_shuffle(c)

# Each time we run these ops, different results are generated
sess = tf.Session()
print(sess.run(norm))
print(sess.run(norm))

# Set an op-level seed to generate repeatable sequences across sessions.
norm = tf.random_normal([2, 3], seed=1234)
sess = tf.Session()
print(sess.run(norm))
print(sess.run(norm))
sess = tf.Session()
print(sess.run(norm))
print(sess.run(norm))

[[-2.8153424 -1.4700928 -1.0456327]
 [-4.0531235 -4.6960516 -4.3747063]]
[[-0.19261467 -8.070787    4.5949564 ]
 [-2.1045833   0.9329183  -5.2283382 ]]
[[ 0.51340485 -0.255814    0.6519913 ]
 [ 1.3923638   0.37256798  0.20336303]]
[[0.96462417 0.34291974 0.24251089]
 [1.0578597  1.6574976  0.8210897 ]]
[[ 0.51340485 -0.255814    0.6519913 ]
 [ 1.3923638   0.37256798  0.20336303]]
[[0.96462417 0.34291974 0.24251089]
 [1.0578597  1.6574976  0.8210897 ]]


In [379]:
X = tf.placeholder(tf.int32,shape=(None,None))
int1 = sess.run(X,feed_dict={X:[random.choices([1,2,3,4,5,6,7,8],k=5) for _ in range(10)]})
int2 = sess.run(tf.constant([random.choices([1,2,3,4,5,6,7,8],k=5) for _ in range(10)]))
int3 = sess.run(tf.convert_to_tensor([random.choices([1,2,3,4,5,6,7,8],k=5) for _ in range(10)]))
float1= sess.run(tf.random_normal([2, 3], mean=-1, stddev=4))

In [382]:
print(int1,'\n\n',int2,'\n\n',int3,'\n',float1)

[[3 8 5 2 2]
 [6 8 8 3 1]
 [4 6 4 4 5]
 [7 3 4 3 3]
 [3 7 3 7 5]
 [8 4 7 3 1]
 [2 5 4 8 1]
 [8 5 5 5 3]
 [3 6 6 3 1]
 [4 7 4 1 7]] 

 [[6 7 5 3 8]
 [8 7 1 7 6]
 [2 4 6 2 1]
 [6 8 7 6 4]
 [3 4 5 1 7]
 [2 7 7 8 2]
 [1 2 8 2 7]
 [1 7 6 5 4]
 [1 5 4 3 5]
 [4 5 1 7 7]] 

 [[5 7 7 4 5]
 [7 2 4 8 1]
 [7 6 7 3 2]
 [6 2 4 7 1]
 [2 7 7 8 4]
 [5 2 3 3 3]
 [4 1 4 2 1]
 [7 5 5 4 1]
 [4 7 3 2 1]
 [3 4 1 2 8]] 
 [[-7.570314   -1.746789   -4.297021  ]
 [ 3.804409   -6.7013016  -0.62265074]]


In [1]:
######################################################################################################

In [7]:
names = [{i:tf.constant(i,name=i)} for i in list("abcdefgh")]
#names = [i for i in list("abcdefg")]
names
import path
data_path =path.Path(r'E:\my_proj\fog_recognition\ExtendFoGData\fixed_data\VideoMark')
filenames = data_path.files()

In [21]:
def par1(item):
    #tf.parse_tensor()
    rest = tf.strings.split(item,sep="\\")
    return res

In [22]:
filenames =[str(i) for i in filenames]


In [23]:
ds0 = tf.data.Dataset.from_tensor_slices(filenames)
ds0=ds0.map(par1)
iterator = ds0.make_one_shot_iterator()
next_element=iterator.get_next()
for _ in range(8):
    #sess.run(iterator.initializer)
    res = sess.run(next_element)
    print(res,type(res))
    print("----------------")


ValueError: Shape must be rank 1 but is rank 0 for 'StringSplitV2' (op: 'StringSplitV2') with input shapes: [], [].

{<tf.Tensor 'StringJoin:0' shape=() dtype=string>: b'a'} <class 'dict'>
----------------
{<tf.Tensor 'StringJoin:0' shape=() dtype=string>: b'b'} <class 'dict'>
----------------
{<tf.Tensor 'StringJoin:0' shape=() dtype=string>: b'c'} <class 'dict'>
----------------
{<tf.Tensor 'StringJoin:0' shape=() dtype=string>: b'd'} <class 'dict'>
----------------
{<tf.Tensor 'StringJoin:0' shape=() dtype=string>: b'e'} <class 'dict'>
----------------
{<tf.Tensor 'StringJoin:0' shape=() dtype=string>: b'f'} <class 'dict'>
----------------
{<tf.Tensor 'StringJoin:0' shape=() dtype=string>: b'g'} <class 'dict'>
----------------
{<tf.Tensor 'StringJoin:0' shape=() dtype=string>: b'h'} <class 'dict'>
----------------


In [199]:
while True:
    try:
        sess.run(iterator.initializer)
        print(sess.run(next_element))
    except tf.errors.OutOfRangeError:
        break

ValueError: Iterator does not have an initializer.

In [180]:
import random

In [211]:
x = tf.placeholder(shape=[], dtype=tf.int32)
c=tf.cond(tf.greater(x,5),lambda:random.choices([1,2,3],k=2),lambda:random.choices([6,7,8],k=2))

In [236]:
with tf.Session() as session:
	print(session.run(c, feed_dict={x: 10}))
	print(session.run(c, feed_dict={x: 3}))
	print(session.run(c, feed_dict={x: 5}))

[2, 3]
[7, 6]
[7, 6]


In [256]:
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])
x = tf.placeholder(shape=[], dtype=tf.int32)
c=tf.case([(tf.greater(x,5),lambda:a),(tf.less(x,5),lambda:b)],lambda: tf.constant(-1))

with tf.Session() as session:
	print(session.run(c, feed_dict={x: 10}))
	print(session.run(c, feed_dict={x: 3}))
	print(session.run(c, feed_dict={x: 5}))
    
d = tf.cond(tf.greater(x,5),lambda:a,lambda:b)
with tf.Session() as session:
	print(session.run(d, feed_dict={x: 10}))
	print(session.run(d, feed_dict={x: 3}))
	print(session.run(d, feed_dict={x: 5}))

[1 2 3]
[4 5 6]
-1
[1 2 3]
[4 5 6]
[4 5 6]


In [287]:
i = tf.constant(0)
c = lambda i: tf.less(i, 10)
b = lambda i: tf.add(i, 1)
r = tf.while_loop(c, b, [i])
print(sess.run(r))
print("===========================================")
i = tf.constant(0)
loop = tf.while_loop(lambda i: i < 10, lambda i: i + 1, [i])
with tf.Session():
    print(loop.eval())
    
def cond(i, n):
    return i < n

def body(i, n):
    i = i *2
    print(i)
    return i, n
i, n = tf.while_loop(cond, body, [2, 17])
print(sess.run([i,n]))

10
10
Tensor("while_44/mul:0", shape=(), dtype=int32)
[32, 17]


In [306]:
sequence = np.array([[1,3],[2,3],[3,4]])

def generator():
    for el in sequence:
        yield el
dataset = tf.data.Dataset.from_generator(generator,output_types=tf.float32,output_shapes=[2])


In [307]:
it = dataset.make_one_shot_iterator()
ne =  it.get_next()
while True:
    try:
        print(sess.run(ne))
    except tf.errors.OutOfRangeError:
        break

[1. 3.]
[2. 3.]
[3. 4.]


In [75]:
import random
def parse_csv_row(item):
    res={item.name:tf.read_file(item)}
    return res

In [76]:
TRAIN_DATA_FILES_PATTERN = 'data/train-*.csv'
import path
data_path ='E:/my_proj/fog_recognition/ExtendFoGData/fixed_data/VideoMark/*.csv'
#filenames = path.Path(data_path).files()
fp = r'E:\my_proj\fog_recognition\recognition_pre_fog_tf\notebook\data\train-data.csv'
filenames =tf.matching_files(data_path)
ds = tf.data.Dataset.from_tensor_slices(filenames)
ds = tf.data.Dataset.from_tensor_slices(tf.gfile.Glob(data_path))
#filenames = tf.absgfile.ListDirectory(data_path)
#tf.gfile.Glob(data_path)
#sess.run(filenames)
#dataset = tf.data.TextLineDataset(filenames)
data =ds.map(parse_csv_row)
iterator = data.make_one_shot_iterator()
next_element=iterator.get_next()

In [77]:
dst= tf.data.Dataset.from_tensor_slices(tf.gfile.Glob(data_path))

In [78]:
while True:
    try:
        print(sess.run(next_element))
    except tf.errors.OutOfRangeError:
        break

{'arg0:0': b'label_start_time,label_end_time,gait_type,label_confidence,stimulate_type,start_time,end_time,unit_confidence\r\n0,8,I,1,,3251751,3252650,0.4\r\n12,13,D,0.2,,3252951,3253150,0.4\r\n17,18,D,0.4,,3253451,3253650,0.4\r\n19,25,D,0.6,,3253651,3254350,0.4\r\n26,26,D,0.4,,3254351,3254450,0.4\r\n27,37,J,0.6,,3254451,3255550,0.4\r\n38,50,H,1,,3255551,3256850,0.4\r\n51,51,H,0.8,,3256851,3256950,0.4\r\n52,57,D,0.5,,3256951,3257550,0.4\r\n58,63,C,0.3,,3257551,3258150,0.4\r\n64,78,H,0.9,,3258151,3259650,0.4\r\n79,82,A,0.6,,3259651,3260050,0.4\r\n83,86,J,0.6,,3260051,3260450,0.4\r\n87,89,H,0.6,,3260451,3260750,0.4\r\n90,104,H,0.9,,3260751,3262250,0.4\r\n105,106,D,0.4,,3262251,3262450,0.4\r\n107,108,H,0.6,,3262451,3262650,0.4\r\n109,116,H,0.9,,3262651,3263450,0.4\r\n117,119,D,0.4,,3263451,3263750,0.4\r\n120,123,H,0.9,,3263751,3264150,0.4\r\n124,130,G,1,,3264151,3264850,0.4\r\n'}
{'arg0:0': b'label_start_time,label_end_time,gait_type,label_confidence,stimulate_type,start_time,end_time,uni

In [14]:


dataset = dataset.map(parse_csv_row)

Tensor("arg0:0", shape=(), dtype=string)


In [143]:
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()

In [18]:
for _ in range(50):
    print(sess.run(next_element))

OutOfRangeError: End of sequence
	 [[node IteratorGetNext_6 (defined at <ipython-input-17-a863eeb5b2ab>:2)  = IteratorGetNext[output_shapes=[[]], output_types=[DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_6)]]

Caused by op 'IteratorGetNext_6', defined at:
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\kernelapp.py", line 478, in start
    self.io_loop.start()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\zmq\eventloop\ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tornado\ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\zmq\eventloop\zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\zmq\eventloop\zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\zmq\eventloop\zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\ipykernel\zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\IPython\core\interactiveshell.py", line 2728, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\IPython\core\interactiveshell.py", line 2850, in run_ast_nodes
    if self.run_code(code, result):
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\IPython\core\interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-a863eeb5b2ab>", line 2, in <module>
    next_element=iterator.get_next()
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\data\ops\iterator_ops.py", line 421, in get_next
    name=name)), self._output_types,
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\ops\gen_dataset_ops.py", line 2107, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\util\deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\framework\ops.py", line 3274, in create_op
    op_def=op_def)
  File "D:\ProgramLanguageCore\Python\anaconda351\lib\site-packages\tensorflow\python\framework\ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

OutOfRangeError (see above for traceback): End of sequence
	 [[node IteratorGetNext_6 (defined at <ipython-input-17-a863eeb5b2ab>:2)  = IteratorGetNext[output_shapes=[[]], output_types=[DT_STRING], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_6)]]


In [ ]:
dataset = data.TextLineDataset(filenames=file_names)
dataset = dataset.skip(skip_header_lines)

In [ ]:
dataset = tf.data.TextLineDataset('data\\train-data.csv')
input_file_names = tf.train.match_filenames_once(pattern=TRAIN_DATA_FILES_PATTERN)
init = (tf.global_variables_initializer(), tf.local_variables_initializer())

In [31]:
dict(zip(HEADER, columns))

{'alpha': <tf.Tensor 'DecodeCSV_39:3' shape=() dtype=string>,
 'beta': <tf.Tensor 'DecodeCSV_39:4' shape=() dtype=string>,
 'key': <tf.Tensor 'DecodeCSV_39:0' shape=() dtype=int32>,
 'target': <tf.Tensor 'DecodeCSV_39:5' shape=() dtype=float32>,
 'x': <tf.Tensor 'DecodeCSV_39:1' shape=() dtype=float32>,
 'y': <tf.Tensor 'DecodeCSV_39:2' shape=() dtype=float32>}

In [28]:
def parse_csv_row(csv_row):
    columns = tf.decode_csv(csv_row, record_defaults=HEADER_DEFAULTS)  # 返回张量本地列表
    features = dict(zip(HEADER, columns))  # 张量的字典，而且还是本地字典，Python语言对象，张量的数据结构不够用了吧？
    for column in UNUSED_FEATURE_NAMES:
        features.pop(column)  #典型Python列表操作
    target = features.pop(TARGET_NAME)
    return features, target

def process_features(features):
    # 典型字典键值对操作
    features["x_2"] = tf.square(features['x'])
    features["y_2"] = tf.square(features['y'])
    features["xy"] = tf.multiply(features['x'], features['y']) # features['x'] * features['y']
    features['dist_xy'] =  tf.sqrt(tf.squared_difference(features['x'],features['y']))
    
    return features

[[15196, 0.8112191, -0.35508192, b'ax02', b'bx02', 0.38995337],
 {'alpha': b'ax02',
  'beta': b'bx02',
  'key': 17262,
  'target': -7.7214413,
  'x': 0.24147429,
  'y': -1.0556995}]

In [27]:

dataset = data.TextLineDataset(filenames=file_names)
dataset = dataset.skip(skip_header_lines)

{'alpha': <tf.Tensor 'DecodeCSV_39:3' shape=() dtype=string>,
 'beta': <tf.Tensor 'DecodeCSV_39:4' shape=() dtype=string>,
 'key': <tf.Tensor 'DecodeCSV_39:0' shape=() dtype=int32>,
 'target': <tf.Tensor 'DecodeCSV_39:5' shape=() dtype=float32>,
 'x': <tf.Tensor 'DecodeCSV_39:1' shape=() dtype=float32>,
 'y': <tf.Tensor 'DecodeCSV_39:2' shape=() dtype=float32>}

In [16]:
iterator = dataset.make_one_shot_iterator()
next_element = iterator.get_next()
with tf.Session() as sess:
    sess.run(init)
    print(sess.run(input_file_names))
    #print(sess.run(dataset))
    print("==============")
    for i in range(20):
        columns = tf.decode_csv(next_element, record_defaults=HEADER_DEFAULTS)
        print(sess.run(columns),'\n',sess.run(next_element))

[b'data\\train-data.csv']
[17262, 0.24147429, -1.0556995, b'ax02', b'bx02', -7.7214413] 
 b'4554,0.10051707170557876,1.2955174458337284,ax01,bx01,-20.770956632825076'
[19003, 0.12530836, -0.37078774, b'ax02', b'bx02', -6.0008817] 
 b'15196,0.8112191149808337,-0.3550819305486099,ax02,bx02,0.3899533765565255'
[9502, 0.09195055, -0.61742663, b'ax02', b'bx01', -3.9802465] 
 b'19474,-0.11787064759978083,0.6238653118217099,ax02,bx02,5.016727463800235'
[3302, -0.4787028, -0.22541492, b'ax01', b'bx01', 3.7519367] 
 b'11529,-0.012568233321424427,0.6128445291658935,ax01,bx02,30.278346073204702'
[16197, 0.29961985, -0.457031, b'ax02', b'bx02', -35.705055] 
 b'19710,0.03385831765171865,0.8426745068240074,ax02,bx02,15.545556636113083'
[12354, 0.19432136, -0.5721079, b'ax01', b'bx02', -33.327343] 
 b'8122,0.46105974898299296,-0.6101714760168783,ax02,bx01,3.6019083787146724'
[640, -0.29774538, -0.2000615, b'ax01', b'bx01', 1.1973482] 
 b'6092,0.06519160224744172,-0.38465389194738503,ax02,bx01,-1.5133

In [57]:
max_value = tf.placeholder(tf.int64, shape=[])
dataset = tf.data.Dataset.range(max_value)
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()

# Initialize an iterator over a dataset with 10 elements.
sess.run(iterator.initializer, feed_dict={max_value: 10})
for i in range(0,10,2):
    print(sess.run(next_element))

# Initialize the same iterator over a dataset with 100 elements.
sess.run(iterator.initializer, feed_dict={max_value: 100})
for i in range(0,40,5):
    print(sess.run(next_element))

0
1
2
3
4
0
1
2
3
4
5
6
7


In [58]:
def f2(max_value):
    dataset = tf.data.Dataset.range(max_value)
    iterator = dataset.make_initializable_iterator()
    return iterator

In [65]:
it = f2(22)
next_element = it.get_next()

In [67]:
sess.run(it.initializer)
for i in range(0,10,2):
    print(sess.run(next_element))

0
1
2
3
4


In [77]:
def f1(x):
    return tf.matmul(x,[[2.0]])

In [79]:
sess.run(f1([[3.0]]))

array([[6.]], dtype=float32)

In [80]:
X=tf.placeholder(tf.float32,shape=(1,1))

In [81]:
l1=f1(X)

In [90]:
max_value = tf.placeholder(tf.int64, shape=[])
dataset = tf.data.Dataset.range(max_value)
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()

# Initialize an iterator over a dataset with 10 elements.
sess.run(iterator.initializer, feed_dict={max_value: 10})
for i in range(0,10,2):
    print(sess.run(next_element))

0
1
2
3
4


In [91]:
max_value =20
dataset = tf.data.Dataset.range(max_value)
iterator = dataset.make_initializable_iterator()
next_element = iterator.get_next()

# Initialize an iterator over a dataset with 10 elements.
sess.run(iterator.initializer)
for i in range(0,10,2):
    print(sess.run(next_element))

0
1
2
3
4


In [11]:
def data_iterator(max_value):
    dataset = tf.data.Dataset.range(max_value)
    iterator = dataset.make_initializable_iterator()
    return iterator

iterator = data_iterator(10)
next_element = iterator.get_next()
# Initialize an iterator over a dataset with 10 elements.
sess.run(iterator.initializer)
for i in range(0,10,2):
    print(sess.run(next_element))

0
1
2
3
4
